legm0310/SafeTransactionPlatform

client/public/index.html
client/src/App.js
client/src/components/Layout/Login.js
client/src/components/Layout/Login.module.css
client/src/components/UI/Modal.js
client/src/components/UI/Modal.module.css

Layout/Login.js - 로그인 페이지 추가
public/index.html - overlays 포털 div 추가
Modal.js - 재사용 가능한 모달창 추가
App.js - 로그인 라우터 추가

로그인 및 모달창 추가

---

client/package-lock.json
client/package.json
client/src/_actions/type.js
client/src/_actions/user_action.js
client/src/_reducers/index.js
client/src/_reducers/user_reducer.js
client/src/components/AddProduct/AddProduct.js
client/src/components/Auth/Login.js
client/src/components/Auth/Register.js
client/src/components/Auth/Register.module.css
client/src/index.js

_atcions : 중앙 저장소에 저장된 state에 “무슨” 동작을 할 것이지 적어놓는 객체
type.js : action에는 type이 필수로 필요, type을 직접 처럼 선언하거나, 모듈로 저장
user_action.js : Dispatch -> Action, Dispatch에 inline으로 action을 넣는 것이 불편하기 때문에 action객체를 return 해주는 함수를 만들어놓는 것
_reducers
index.js : 여러 개의 reducer을 하나의 root reducer로 만들어주는 것
user_action.js : dispatch -> action, type을 확인해서 그에 맞는 동작을 하는 곳
Auth/Login.js 및 Register.js 로직 추가
index.js redux 로직 추가

Feat: 회원가입 및 로그인 로직 추가

---

server/app.js
server/config/config.json
server/controllers/userController.js
server/models/index.js
server/models/user.js

Feat: 로그인 토큰 발급 구현, 에러처리, db설정 타임존 추가

Feat: 로그인 토큰 발급 구현

---

client/src/App.js
client/src/components/AddProduct/AddProduct.js
client/src/components/AddProduct/AddProduct.module.css
client/src/components/Auth/Login.module.css
client/src/components/Auth/Register.module.css
client/src/components/Purchase/Purchase.js
client/src/components/Purchase/Purchase.module.css
client/src/components/Purchase/PurchaseList.js
client/src/components/Purchase/PurchaseList.module.css

Addproduct.js: 상품등록 로직, 폼에 값들이 입력되어있지 않으면 등록안됨, 이미지 등록 로직
상품등록페이지에서 이미지등록 하는 부분 CSS 변경
로그인 및 회원가입 박스 그림자 추가
Purchase.js: App.js에서 Purchase.js로 보낸 상품등록 값들을 PurchaseList로 보내는 로직 추가
PurchaseList.js파일  추가: 상품등록시 구매페이지에서 등록된 값들이 보여지고 카드가 추가됨
App.js: PurchaseList에 상품등록 값들을 보내는 로직 추가

Feat: 상품카드리스트 js파일추가 및 상품등록한 값들을 상품카드리스트에 보내는 로직추가

---

client/src/App.js
client/src/_actions/user_action.js
client/src/components/AddProduct/AddProduct.js
client/src/components/Auth/Register.js
client/src/components/Home/Home.js
client/src/components/Home/Home.module.css
client/src/components/Layout/DropdownMenu.js
client/src/components/Layout/DropdownMenu.module.css
client/src/components/Layout/Header.js
client/src/components/Layout/Header.module.css
client/src/components/Purchase/DetailPurchase.js
client/src/components/Purchase/Purchase.js
client/src/components/Purchase/Purchase.module.css
client/src/setupProxy.js

user_action.js: /user/login -> /api/user/login, /user/signup -> /api/user/signup
Register.js: navigate("/login") -> navigate("Login")
setupProxy.js 파일 생성
Header.js: 구매하기의 Link를 li안으로 넣었음

Refactor: 로그인/회원가입 엔드포인트 URL 변경, Feat: 프록시 설정을 위한 setupProxy.js파일 생성

---

server/app.js
server/controllers/index.js
server/loaders/dependencyInjector.js
server/loaders/express.js
server/loaders/index.js
server/middlewares/isAuth.js
server/models/product.js
server/models/token.js
server/models/user.js
server/routes/auth.js
server/routes/index.js
server/routes/product.js
server/services/auth.js
server/services/token.js

Comment: loader, routes, authController, authService

Comment: loader, routes, authController, authService

---

client/src/components/AddProduct/AddProduct.js
client/src/components/AddProduct/AddProduct.module.css
client/src/components/Layout/Header.module.css
client/src/components/Purchase/Purchase.module.css
client/src/components/Purchase/PurchaseList.js
client/src/components/Purchase/PurchaseList.module.css

AddProduct.js: onPriceHandler 숫자 입력시 콤마 자동생성 로직
PurchaseList.js: className 추가
Header.module.css: border-bottom 생성
Purchase.module.css: 카테고리박스 UI 변경
PurchaseList.module.css: 상품카드 UI 변경
AddProduct.module.css: input 포커스 시 색 변경, 이미지 등록 박스 색 변경

Feat: 가격 input 숫자 입력시 콤마 자동생성, Design: CSS 변경, Refactor: className추가

---

server/.env.example
server/config/index.js
server/controllers/authController.js
server/loaders/index.js
server/models/index.js
server/models/product.js
server/models/user.js
server/routes/auth.js
server/services/auth.js
server/services/token.js

Feat: logout, product
Chore: NODE_ENV, .env.example 수정

Feat: logout, product

---

server/controllers/authController.js
server/routes/auth.js
server/services/auth.js

Feat: authCheck(test)

---

server/controllers/authController.js

Fix: authCheck 응답 데이터 수정

---

server/loaders/index.js
server/services/token.js

Rename: tokenModel -> Token

---

server/loaders/express.js
server/services/auth.js
server/services/index.js
server/services/product.js
server/services/user.js

Fix: authCheck시 비밀번호 노출 수정, Unauthorized 데이터 전달

Fix: authCheck시 비밀번호 노출 수정

---

server/controllers/index.js
server/controllers/productController.js
server/routes/product.js

Feat: productRoute, productController

Feat: productRoute, productController

---

server/controllers/productController.js
server/middlewares/isAuth.js
server/services/auth.js
server/services/product.js
server/services/token.js
server/services/user.js

Feat: productService에 deleteProduct함수 추가, 
Fix: userService에 getUserByEmail 메서드에 force:true옵션 delete메서드로 옮김
기타 주석 변경

Feat: productService 함수 추가

---

server/utils/catchAsync.js

Refactor: catchAsync try-catch문 중복 제거

Refactor: catchAsync try-catch문 중복 제거

---

client/src/_actions/type.js
client/src/_actions/user_action.js
client/src/_reducers/user_reducer.js
client/src/components/Auth/Login.js
client/src/components/Auth/Register.js
client/src/components/Layout/Header.js
client/src/components/Layout/UserAuth.js
client/src/components/Layout/UserAuth.module.css
client/src/hoc/auth.js

Feat: 로그인 및 회원가입 로직 설정 

---

server/controllers/authController.js
server/routes/auth.js
server/services/auth.js
server/services/token.js
server/utils/catchAsync.js

Refactor: 서비스 계층 에러 처리 중앙화 (try-catch문 제거)
Fix: removeToken, logout router 버그(문법 ,미들웨어 부적절한 적용)

Refactor: 서비스 계층 에러

---

client/src/_actions/user_action.js
client/src/hoc/auth.js

user_action.js: const headers = { Authorization: accessToken }; 변수처리
hoc/auth.js: dispatch 부분 localStorage.removeItem("accessToken");추가

Feat: accessToken 제거코드, Refactor: auth 함수

---

server/services/auth.js

Fix: 토큰 중복생성 수정

---

client/src/_actions/user_action.js
client/src/components/AddProduct/AddProduct.js
client/src/components/AddProduct/AddProduct.module.css
client/src/components/Auth/Login.js
client/src/components/Layout/UserAuth.js
client/src/hoc/auth.js

user_action.js: loginUser 에러 catch
AddProduct.js: 유효성검사, 이미지 여러개 등록, 이미지삭제핸들러
Login.js: 유효성검사, dispatch
UserAuth.js: 로그인핸들러 loginSuccess 지움
auth.js: hoc으로 감싸진 컴포넌트 props 사용가능하게 만듬

Refactor: loginUser 에러catch, onImgFileHandler, onSubmitHandler, onLogoutHandler, Feat:deleteImgHandler, AuthenticationCheck return, 유효성 검사, 

---

client/src/_actions/user_action.js

Fix: action 함수 오타 수정

---

client/src/App.js

Fix: token 여부 검사 로직 수정

---

server/config/index.js
server/loaders/express.js

Feat: cors옵션 추가, config 도메인추가

---

server/config/index.js
server/controllers/authController.js
server/loaders/express.js
server/middlewares/index.js
server/middlewares/secure.js
server/routes/auth.js
server/routes/product.js

Feat: secure middleware
-> 취약한 부분에 대한 요청 거부
Refactor: middleware 리팩토링
Fix: cors 문제 해결

Feat: secure middleware 구현

---

server/controllers/authController.js
server/services/auth.js
server/services/token.js
server/services/user.js

Refactor: signupController, signupService - 회원 가입 시 불필요한 토큰 생성 삭제,
tokenService - 로그아웃 함수 토큰 삭제 시 토큰 조회 2번 실행 수정,
userService - findOne 사용 메소드 예외처리 -> 외부 함수에서 예외처리

Refactor: signupController, signupService, tokenService, userService

---

client/src/_actions/user_action.js
client/src/components/Auth/Login.js
client/src/components/Auth/Register.js

Refactor: login, register, action
login -> 에러처리 수정
register -> 에러처리 수정
action -> withCredentials 수정

Refactor: login, register, action

---

server/services/token.js

Refactor: tokenService -> findOne을 사용하는 메서드의 에러 처리를 외부로 넘김

Refactor: tokenService

---

client/src/_actions/user_action.js

Refactor: action baseURL 설정

---

client/src/App.js
client/src/_actions/user_action.js

Refactor: action 함수 -> axios 쿠키 사용 옵션, BaseURL 등 전역으로 설정
Fix: 경로 수정 (Login -> login 등)

Refactor: action 함수

---

client/src/App.js

Fix: 로그인 검사 수정

---

client/src/components/Auth/Register.js

Fix: 경로 오타 수정

---

server/config/index.js
server/config/passport.js
server/controllers/authController.js
server/controllers/productController.js
server/loaders/express.js
server/middlewares/error.js
server/middlewares/index.js
server/middlewares/isAuth.js
server/middlewares/uploader.js
server/routes/auth.js
server/routes/index.js
server/routes/product.js
server/services/auth.js
server/services/product.js
server/services/token.js
server/utils/index.js
server/utils/s3Upload.js

Feat: uploader추가
Refactor: utils 기능 리팩토링
Comment: config 알아보기 쉽게 주석 추가
Fix: productRoute 운용

Feat: uploader추가

---

server/config/index.js
server/loaders/sequelize.js
server/middlewares/uploader.js
server/package-lock.json
server/package.json
server/routes/product.js
server/utils/s3Upload.js

Chore: aws-sdk v3로 수정, 선언부 수정
테스트용 코드 제거

Chore: aws-sdk v3로 수정, 선언부 수정

---

client/src/_actions/product_action.js
client/src/components/AddProduct/AddProduct.js
client/src/components/Home/Home.js

Feat: addProduct formData 추가, product action 추가
Co-authored-by: legm0310 <legm0310@gmail.com>
Co-authored-by: LeeSeungHoon <ysh73900@gmail.com>

Feat: addProduct formData 추가, product action 추가

---

client/src/_actions/product_action.js

Fix: error test용 console.log 제거
Co-authored-by LeeSeungHoon <ysh73900@gmail.com>

Fix: error test

---

server/middlewares/uploader.js
server/routes/product.js
server/utils/s3Upload.js

Fix: upload middleware 수정, multer-s3 contentType에 AUTO_CONTENT_TYPE추가 -> 버킷의 url 접속시 브라우저로 이미지 확인 가능

Fix: upload middleware 수정

---

client/src/_actions/product_action.js
client/src/_actions/user_action.js
client/src/components/AddProduct/AddProduct.js
client/src/components/Purchase/Purchase.js

Feat: addProduct action 헤더 추가, upload 필드 수정
Fix: product 선언부 누락 수정

Feat: addProduct action 헤더 추가, upload 필드 수정

---

server/middlewares/isAuth.js
server/middlewares/uploader.js
server/routes/product.js

Fix: auth 토큰 재발급 로직 오류 수정
Test: upload test추가

Fix: auth 토큰 재발급 로직 오류 수정

---

client/src/components/Purchase/Detail.js
client/src/components/Purchase/Detail.module.css
client/src/components/Purchase/Purchase.js
client/src/components/Purchase/PurchaseCard.module.css

Detail.js: 상세페이지 상품정보 및 상점정보 UI 추가

Design: 상품 상세페이지 상품정보 및 상점정보

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/_actions/type.js
client/src/_reducers/index.js
client/src/_reducers/productReducer.js
client/src/_reducers/userReducer.js
client/src/components/AddProduct/AddProduct.js
client/src/components/Auth/Login.js
client/src/components/Layout/Header.js
client/src/components/Layout/UserAuth.js
client/src/index.js

Refactor: addProduct 이미지 업로드 수정
Rename: redux 객체 타입명 변경
Comment: redux toolkit 주석
Co-authored-by: LeeSeungHoon <kim73900@naver.com>

Refactor: props제거 redux store사용, reducer 분할

---

server/controllers/productController.js
server/loaders/sequelize.js
server/middlewares/isAuth.js
server/middlewares/uploader.js
server/routes/product.js
server/utils/generalError.js
server/utils/index.js
server/utils/s3Upload.js

Feat: InternalServerError추가, image삭제, getImgUrlByKey 추가
Fix: sequelize 로더 에러핸들링, isAuth 선언부 추가
Comment: productController주석 추가, uploader주석 제거
Test: addProduct 테스트

Feat: InternalServerError, image삭제 기능, getImgUrlByKey 기능 추가

---

server/config/validSchema.js
server/middlewares/validation.js

Feat: validSchema의 유효성 검증 내용 추가

Feat: 유효성 검증

---

server/config/validSchema.js
server/controllers/productController.js
server/loaders/express.js
server/middlewares/error.js
server/middlewares/uploader.js
server/middlewares/validation.js
server/models/product.js
server/routes/product.js
server/services/product.js

Fix: signup 유효성 검증 id 제거 및 예외 처리(커스텀 에러) 수정
Co-authored-by: Junyoung Jeon <wns0818@naver.com/patric7732>

Fix: signup 유효성 검증 id 제거 및 예외처리 수정

---

client/src/components/AddProduct/AddProduct.js

Fix: formData에 json데이터 추가

---

client/src/_actions/productAction.js
client/src/_actions/userAction.js
client/src/_reducers/userReducer.js
client/src/api/common.js
client/src/api/productApi.js
client/src/components/Auth/Login.module.css
client/src/components/Home/Home.module.css
client/src/components/Layout/Header.js
client/src/components/Layout/Header.module.css
client/src/index.css
client/src/utils/index.js
client/src/utils/storage.js

Refactor: axios요청 모듈화
Design: 폰트 변경, 버튼 및 검색창 색 변경

Refactor: axios요청 모듈화

---

server/models/product.js
server/models/user.js

Fix: db 관계 설정 오류 수정

---

server/controllers/productController.js
server/models/chatLog.js
server/models/index.js
server/models/product.js
server/models/productImage.js
server/routes/product.js
server/services/product.js

Fix: url 수정
Feat: getProduct
Comment: product model 주석 추가
Rename: chatContent, chatLog로 변경

Feat: getProduct 구현

---

client/src/App.js
client/src/_reducers/userReducer.js
client/src/components/Layout/Logo.js
client/src/components/Layout/MobileNavMenu.js
client/src/components/RecentProductsList.js
client/src/components/UI/Button.js
client/src/pages/Auth/Login.js
client/src/pages/Auth/Register.js
client/src/pages/Product/Detail.js
client/src/pages/Product/DetailSlide.js
client/src/pages/Product/Product.js
client/src/styles/AddProduct.module.css
client/src/styles/Button.module.css
client/src/styles/Home.module.css
client/src/styles/Login.module.css
client/src/styles/Logo.module.css
client/src/styles/Product.module.css
client/src/styles/RecentProductsList.module.css
client/src/styles/Register.module.css

Feat: 리렌더링시 로그인여부확인, 재사용 버튼 컨포넌트
Fix: url 수정
Refactor: 로고 라이브러리 사용X, Link사용, 사용하지않는 함수 삭제 및 Link 삭제

Feat: 리렌더링시 로그인여부확인, 재사용 버튼 컨포넌트 Fix: url 수정, Refactor: 로고 라이브러리 사용X, Link사용

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/components/Layout/DesktopNavMenu.js
client/src/components/RecentProductsList.js
client/src/components/UI/Loading.js
client/src/pages/AddProduct/AddProduct.js
client/src/pages/Auth/Register.js
client/src/pages/Home/HomeSlide.js
client/src/pages/Product/DetailSlide.js
client/src/styles/AddProduct.module.css
client/src/styles/Header.module.css
client/src/styles/Home.module.css
client/src/styles/Loading.module.css

Feat: loading spinner 생성
Feat: styled-components, react-spinners
Fix: 디자인으로 인한 코드 수정
Feat: dispatch alert 추가
Feat: 각각 상품카드 Link
Design: arrow 생성

Feat: loading spinner 생성

---

client/src/App.js
client/src/components/Layout/Header.js
client/src/components/RecentProductsList.js
client/src/components/UI/Loading.js
client/src/components/UI/ScrollTop.js
client/src/styles/RecentProductsList.module.css

Design: 헤더 고정
Fix: 오타 수정
Design: 상품카드 css 변경
Fix: 키값이 포함된 div 위치 변경
Feat: 페이지이동시 화면 최상단으로 스크롤

Feat: 페이지이동시 화면 최상단으로 스크롤

---

client/src/pages/Product/Detail.js
client/src/styles/Detail.module.css

Design: 상세페이지 버튼 디자인 변경

---

client/src/_actions/userAction.js
client/src/components/Layout/DesktopNavMenu.js
client/src/components/Layout/MyWallet.js
client/src/components/Layout/UserSection.js
client/src/index.js

Merge: client -> dev

---

client/src/App.js
client/src/components/Layout/UserSection.js
client/src/pages/User/UserAddProduct.js
client/src/pages/User/UserInfo.js
client/src/pages/User/UserPurchaseProduct.js
client/src/pages/User/UserWishList.js
client/src/styles/UserInfo.module.css

Feat: 내정보 컴포넌트 생성
Feat: 내정보 컴포넌트 라우트
Feat: 내정보 판매상품, 구매상품, 찜목록 데이터 컴포넌트
Feat: 내정보 링크추가
Design: 내정보 CSS

Feat: 내정보 컴포넌트 생성

---

server/models/chatLog.js
server/models/chatRoom.js
server/models/index.js

Rename: 
ChatParticipant -> ChatLog로 변경

Rename: ChatParticipant, ChatLog로 변경

---

server/models/chatLog.js
server/models/chatRoom.js

Rename: 
ChatLog, ChatRoom 모델
카멜 표기법에서 스네이크 표기법으로 수정 완료.

Rename: ChatLog, ChatRoom 모델 스네이크 표기법으로 수정

---

server/controllers/chatController.js
server/models/chatLog.js
server/models/chatRoom.js

Rename: 
chatLog, chatRoom 모델 속성 이름 수정
+ chatController 추가

Rename: chatLog, chatRoom 모델 속성 이름 수정

---

client/src/App.js
client/src/components/Layout/MyWallet.js
client/src/components/Layout/UserSection.js
client/src/components/RecentProductsList.js
client/src/pages/Home/HomeSlide.js
client/src/pages/Product/Detail.js
client/src/pages/User/UserInfo.js
client/src/styles/HomeSlide.module.css
client/src/styles/RecentProductsList.module.css
client/src/styles/UserInfo.module.css

Feat: mui/material 헤더부분 글씨체 적용
Design: 헤더 디자인 변경
Design: 홈슬라이드 수정
Design: className 변경 및 디자인 수정
Fix: className 변경
comment: 주석삭제
Merge remote-tracking branch 'lgm/feat/client'

Design: 헤더 디자인 변경

---

client/src/_actions/roomAction.js
client/src/_actions/type.js
client/src/_reducers/chatReducer.js
client/src/components/Layout/UserSection.js
client/src/pages/Product/Detail.js

Feat:
UserSection, Detail 페이지의
'판다톡'에 /chat으로 연결되는 Link 추가

Feat: UserSection, Detail 페이지 '판다톡'에 chat으로 연결되는 Link 추가

---

server/controllers/chatController.js
server/controllers/index.js
server/models/chatRoom.js
server/routes/chat.js
server/routes/index.js
server/services/chat.js
server/services/index.js

Feat:
Chat 관련 Controller, routes, services 추가 및 addRoom 구현

Feat: Chat Controller, routes, services 추가 및 addRoom 구현

---

client/src/components/Layout/MyWallet.js
client/src/components/Layout/UserSection.js
client/src/components/User/Exchange.js
client/src/pages/User/ReservedProduct.js
client/src/styles/ReservedProduct.module.css
client/src/styles/UserInfo.module.css

Fix: 사용하지않는 코드 삭제
Feat: Exchange Modal 라이브러리 사용
Feat: Exchange handle함수 추가
Fix: 내정보의 구매진행상품 하드코딩
Design: css 변경
Merge remote-tracking branch 'lgm/feat/client'

Feat: Exchange Modal 라이브러리 사용 및 Exchange handle함수 추가

---

contract/contracts/CommonFnWrapper.sol
contract/contracts/PandaToken.sol
contract/contracts/Platform.sol
contract/contracts/SafeTxn.sol
contract/contracts/interface/IEscrow.sol
contract/contracts/interface/ISafeTxn.sol

Merge: contract -> dev

---

server/controllers/productController.js
server/loaders/express.js
server/middlewares/secure.js
server/package-lock.json
server/package.json
server/routes/product.js
server/services/product.js
server/utils/dataParsers.js

Merge: server -> dev

---

contract/contracts/SafeTxn.sol

Merge: contract-> dev

---

server/controllers/chatController.js
server/loaders/sequelize.js
server/loaders/socket.js
server/routes/chat.js

Feat:
roomId 검색 Controller 추가 및 메시지 전송 socket 추가

Feat: roomId 검색 Controller 추가 및 메시지 전송 socket 추가

---

client/src/pages/Chat/Chat.js
client/src/pages/Chat/Chatroom.js
client/src/pages/Chat/Input.js

Feat: Chat에 socket 기능 연동

---

client/src/components/user/WishList.js
client/src/styles/user/UserInfo.module.css
client/src/styles/user/WishList.module.css

Design: 찜목록 디자인
Design: css 변경

Design: 찜목록 디자인

---

server/controllers/productController.js
server/loaders/sequelize.js
server/routes/product.js
server/services/product.js

Feat: WishList GET / POST / DELETE Method 추가

Feat: WishList GET / POST / DELETE API 추가

---

client/src/components/chat/Chatroom.js
client/src/pages/Chat/Chat.js

Rename: 파스칼케이스로 변경

---

server/controllers/index.js
server/controllers/productController.js
server/controllers/userController.js
server/loaders/socket.js
server/routes/index.js
server/routes/product.js
server/routes/user.js
server/services/product.js
server/services/user.js

Refactor: wishList 관련 함수 product에서 user로 이동

Refactor: wishList 관련 함수 product에서 user로 이동

---

client/src/pages/Product/Product.js
client/src/pages/Product/ProductCard.js

Feat: ProductCard API 연동

---

client/src/_actions/productAction.js
client/src/components/headers/DesktopNavMenu.js
client/src/components/headers/MobileNavMenu.js
client/src/pages/Product/Product.js

Feat: 구매하기 URL에 category, search 파라미터 기본값 추가
Feat: 상품 검색&카테고리 병행 제어 기능 추가

Feat: 구매하기 URL에 파라미터 기본값 추가 및 검색 기능 보완

---

client/src/_actions/productAction.js
client/src/_reducers/userReducer.js
client/src/index.css
client/src/pages/Product/Product.js
client/src/styles/headers/Header.module.css
client/src/styles/product/Product.module.css
client/src/styles/product/ProductCard.module.css

Design: className 추가
Fix: 제품상세 무한로딩 해결
Fix: loadWishList 배열로 변경
Design: css 변경

Fix: 제품상세 무한로딩 해결

---

client/src/components/detailProduct/ProductInformation.js
client/src/components/detailProduct/ProductStore.js
client/src/styles/product/Detail.module.css

Feat: 제품 상세 페이지의 상품 설명에 개행 문자 적용
Feat: 판매자 정보 판매자 이름 추가
Design: 판매자정보 디자인

Feat: 제품 상세 페이지 기능 추가

---

client/src/components/common/Modal.js
client/src/components/headers/MyWallet.js
client/src/components/user/WishList.js
client/src/styles/headers/MyWallet.module.css

Rename: css 파일 경로 변경
Design: 지갑모달 디자인 변경
Design: MyWallet css파일 생성
Fix: 키 오류 제거
Merge: pull request

Fix: 키 오류 제거

---

client/src/App.css
client/src/App.js
client/src/components/Footer/Footer.js
client/src/components/headers/MyWallet.js
client/src/components/product/ProductCard.js
client/src/components/product/RecentProducts.js
client/src/components/user/ReservedProduct.js
client/src/components/user/WishItem.js
client/src/components/user/WishList.js
client/src/index.css
client/src/pages/Product/Product.js
client/src/styles/Footer/Footer.module.css
client/src/styles/headers/Header.module.css
client/src/styles/headers/MyWallet.module.css
client/src/styles/product/Product.module.css
client/src/styles/product/ProductCard.module.css
client/src/styles/product/RecentProducts.module.css
client/src/styles/user/OnSaleProduct.module.css
client/src/styles/user/PurchasedProduct.module.css
client/src/styles/user/ReservedProduct.module.css
client/src/styles/user/UserInfo.module.css
client/src/styles/user/WishList.module.css

Fix: 찜목록 버그 수정
Design: 지갑 UI 개선
Feat: footer 생성
Merge: pull request

찜목록 버그 수정 및 지갑 UI 개선 및 Footer 생성

---

server/controllers/userController.js
server/routes/user.js
server/services/auth.js
server/services/user.js

Refactor: getUser함수 변경

---

client/src/components/Footer/Footer.js
client/src/components/chat/ChatRoom.js
client/src/pages/Chat/Chat.js
client/src/pages/DetailProduct/Detail.js
client/src/styles/Footer/Footer.module.css
client/src/styles/chat/Chat.module.css
client/src/styles/product/Detail.module.css

Feat: 소켓 연결 옵션 추가
Design: 채팅방 UI 개선
Design: 상세페이지 UI 개선
Design: footer UI 개선

Design: 채팅방 UI 개선

---

client/src/App.js
client/src/_actions/type.js
client/src/_actions/userAction.js
client/src/_reducers/userReducer.js
client/src/components/headers/UserMenu.js
client/src/pages/User/UserInfo.js
client/src/styles/user/UserInfo.module.css

Feat: UserInfo 프로필 내용 추가

---

client/src/App.js
client/src/components/Banner/Banner.js
client/src/components/Home/HomeSlide.js
client/src/components/chat/Chats.js
client/src/components/headers/Header.js
client/src/pages/User/UserInfo.js
client/src/styles/banner/Banner.module.css
client/src/styles/chat/Chat.module.css
client/src/styles/home/Home.module.css
client/src/styles/home/HomeSlide.module.css
client/src/styles/product/ProductCard.module.css
client/src/styles/product/RecentProducts.module.css
client/src/styles/user/UserInfo.module.css

Design: 채팅방 UI 개선
Design: 헤더 스크롤 내릴시 UI 변화
Feat: 배너 페이지

채팅방 UI 개선 및 배너 추가

---

server/controllers/userController.js
server/loaders/sequelize.js
server/models/user.js
server/routes/user.js
server/services/user.js

UserInfo 컴포넌트에서 쓰일 유저 정보 수정 기능에 사용될 API

Feat: user_name 및 introduce 수정 기능 추가

---

client/src/_actions/type.js
client/src/_actions/userAction.js
client/src/_reducers/userReducer.js
client/src/components/user/UserProfile.js
client/src/components/user/WishItem.js
client/src/pages/User/UserInfo.js
client/src/styles/user/UserInfo.module.css

떨어지는 가독성으로 인한 UserProfile 컴포넌트 분리
유저 정보 수정 기능 추가

Feat: User Name/Introduce 수정 API 추가

---

server/controllers/userController.js
server/routes/user.js
server/services/user.js

updateUserName / updateIntroduce 두 함수를 updateUser 함수 하나로 통일

Refactor: 유저 이름, 소개글 수정 updateUser 함수 하나로 통일

---

client/src/_reducers/userReducer.js
client/src/components/Headers/UserMenu.js
client/src/components/User/ReservedProduct.js
client/src/components/User/UserProfile.js
client/src/styles/user/UserInfo.module.css

Refactor: 리덕스 스토어 리팩토링

---

client/src/components/Detail/ProductSellor.js
client/src/components/Footer/Footer.js
client/src/components/User/UserProfile.js
client/src/pages/Detail/Detail.js
client/src/styles/Footer/Footer.module.css

Feat: Insta 링크 추가
Chore: 불필요한 주석 삭제
Fix: classname 오타 수정

Feat: 프로필로 가는 링크 사진 포함

---

client/src/components/Home/HomeSlide.js

Design: 홈슬라이드 화살표 위치 조정

---

client/src/components/Footer/Footer.js

Design: 글자 위치 상하 조절

---

client/src/components/Manual/Manual.js

Feat: 메뉴얼 하단 링크 추가

---

client/src/components/Headers/DesktopNavMenu.js
client/src/components/Headers/MobileNavMenu.js
client/src/components/common/Paging.js
client/src/pages/Product/Product.js
client/src/styles/common/Paging.css

Design: 페이지네이션 디자인
Feat: 구매하기 페이지 페이지네이션 기능 구현
Refactor: 구매하기 링크 URL 수정

Feat: 페이지네이션 구현

---

client/src/pages/Product/Product.js

Feat: 페이지네이션 스트링 쿼리 추가

---

client/src/components/Detail/RelatedProduct.js
client/src/pages/Detail/Detail.js
client/src/styles/detail/Detail.module.css

Feat: 연관 상품 컴포넌트 생성 및 기능 구현
Rename: Relation -> Related로 수정

Feat: 연관 상품 컴포넌트 생성 및 기능 구현

---

client/src/components/Footer/Footer.js
client/src/components/Headers/DesktopNavMenu.js
client/src/components/Headers/Header.js
client/src/pages/User/UserInfo.js
client/src/styles/home/Home.module.css
client/src/styles/product/ProductCard.module.css
client/src/styles/product/RecentProducts.module.css

Merge: pull request
Fix: linearGradient -> li
Design: 검색바 UI 개선, Header UI 개선, Home 첫번째 섹션의 중간타입 글씨 수정, ProductCard UI 개선, 더보기 버튼 UI 개선
Feat: 판매자의 내정보 구분

Feat: 판매자의 내정보 구분

---

client/src/components/Footer/Footer.js
client/src/components/Headers/DesktopNavMenu.js
client/src/components/Headers/Header.js
client/src/components/Headers/MobileNavMenu.js
client/src/components/Headers/UserAuth.js
client/src/components/Headers/UserMenu.js
client/src/components/Product/RecentProducts.js
client/src/styles/Footer/Footer.module.css
client/src/styles/headers/Logo.module.css
client/src/styles/home/Home.module.css
client/src/styles/home/HomeSlide.module.css
client/src/styles/product/ProductCard.module.css
client/src/styles/product/RecentProducts.module.css
client/src/styles/user/UserInfo.module.css

Docs: 푸터.js div에 클래스명 추가
Design: 데스크탑메뉴 반응형(구매, 판매, 검색) 제작
Design: 헤더 반응형 기존과 다르게 변경 
Design: 모바일nav 변경 - 미완성
Design: 로그인 로그아웃 반응형으로 안보이게 변경
Design: 유저메뉴 1200px이하로는 햄버거로 변경 - 미완성
Docs: logo.module.css 불필요한 css 제거
Docs: 상품 카드 넓이 고정값 주석처리
Design: 메인 홈페이지 최근상품 가운데 정렬

Design: 반응형 1260px -> 1200px, 980px -> 900px, 500px -> 600px으로 수정

---

client/src/components/Product/RecentProducts.js
client/src/pages/Product/Product.js
client/src/styles/home/Home.module.css
client/src/styles/product/Product.module.css
client/src/styles/product/ProductCard.module.css
client/src/styles/product/RecentProducts.module.css

Comment: 임시 주석처리
Fix: div 선언
Design: UI 개선
Merge: pull request

Merge: pull request

---

client/src/App.js
client/src/_actions/type.js
client/src/_actions/userAction.js
client/src/_reducers/chatReducer.js
client/src/_reducers/userReducer.js
client/src/components/Headers/UserMenu.js

WishList State 유지와 안 읽은 메시지 수 출력을 위한 API 생성 및 적용

Feat: getInitUser API 추가

---

client/src/components/Detail/ProductSellor.js
client/src/components/Detail/RelatedProduct.js
client/src/pages/Detail/Detail.js
client/src/styles/detail/Detail.module.css

Feat: 찜하기 버튼 전후 상태 변경 기능 추가

---

client/src/components/Headers/DesktopNavMenu.js
client/src/components/Headers/MobileNavMenu.js
client/src/components/Headers/UserMenu.js

Fix: 헤더 튀어나온거 제거
Docs: 불필요한 코드 제거

Refactor: 헤더 반응형 슬라이드로 변경

---

client/src/components/User/UserProfile.js
client/src/pages/Detail/Detail.js

Feat: Detail 페이지에 찜개수 표시
Feat: Detail 로그인 인증 추가
Feat: UserProfile에 채팅 버튼 표시

Feat: Detail, UserProfile 기능 추가

---

client/src/components/User/ReservedProduct.js
client/src/styles/user/ReservedProduct.module.css
client/src/styles/user/WishList.module.css

Design: 판매진행상품 UI 개선
Comment: 필요없는 주석 및 내용 삭제

Design: 판매진행상품 UI 개선

---

server/services/product.js
server/services/user.js

Feat: getProducts API에 제품 찜 개수 포함
Chore: 필요 없는 주석 제거

Feat: getProducts API에 제품 찜 개수 포함

---

client/src/components/Chat/Chats.js
client/src/components/Chat/Search.js
client/src/components/Chat/Sidebar.js
client/src/components/Footer/Footer.js

Feat: 발표자료 링크 및 채팅방 검색 기능 추가

---

client/src/components/Chat/ChatRoom.js
client/src/components/User/UserProfile.js
client/src/styles/user/UserInfo.module.css

Feat: 채팅방의 상대방 userName 누르면 상대방 프로필 이동 기능 추가

---

client/src/_reducers/chatReducer.js
client/src/components/Chat/Chats.js
client/src/components/Receipt/DepositReceipt.js
client/src/components/User/PurchasedList.js
client/src/components/User/ReservedList.js
client/src/styles/chat/Chat.module.css
client/src/styles/user/ReservedList.module.css

Feat: 구매진행정보 모달창 생성, 구매진행정보 모달창 UI 및 핸들러 기능 추가
Fix: 메세지 읽음 처리 로직 수정, 모달창 열기/닫기 상태변수 이름 변경
Design: 안읽은 메세지 갯수 디자인 개선, 구매진행정보 버튼 CSS 추가

Fix: 메세지 읽음 처리 로직 수정

---

client/src/components/Chat/Search.js
client/src/components/Chat/Sidebar.js
client/src/components/Headers/DesktopNavMenu.js
client/src/components/User/UserProfile.js
client/src/components/User/WishItem.js
client/src/styles/chat/Chat.module.css
client/src/styles/headers/Header.module.css

Feat: 찜목록 가격 천단위 콤마 추가
Feat: 채팅 및 헤더 검색창 입력값 초기화 기능 추가

Fix: 타유저 상세정보에서 내 프로필로 갔을 때 리렌더링 되지 않던 오류 해결

---

client/src/components/Detail/DetailSlide.js
client/src/pages/AddProduct/AddProduct.js
client/src/styles/addProduct/AddProduct.module.css
client/src/styles/detail/Detail.module.css

Fix: addProduct.js 부분 카테고리 value 값 변경
Design: DetailSlide.js의 slick-dots UI 개선, Detail.js의 이미지슬라이드부분 width값 변경,  addProduct.js의 이미지박스 margin-bottom 추가
Merge: branch lgm into feat/client

Design: slick-dots UI 개선

---

client/src/components/Headers/MyWallet.js
client/src/components/Receipt/ReleaseReceipt.js
client/src/components/Receipt/TransacDetailReceipt.js
client/src/components/User/PurchasedList.js
client/src/pages/User/UserInfo.js
client/src/styles/receipt/ReleaseReceipt.module.css
client/src/styles/receipt/TransactionDetailReceipt.module.css

Feat: 거래내역(영수증) 모달창에 activeMenu 기능 추가, 거래내역 activeMenu에 렌더링될 js파일 생성
Fix: 거래완료상품 버튼 텍스트 변경,  userInfo.js 필요없는 리덕스 함수 제거
Design: 내지갑 모달창 UI 개선, 거래내역 모달창의 activeMenu CSS 추가, 거래내역(영수증) CSS 추가

Feat: activeMenu 기능 추가

---

server/services/product.js
server/services/user.js

Rename: addWishList Redux State 키값 product_id->id

Feat: getProductById, hasWishList 추가

---

client/src/components/Headers/UserMenu.js
client/src/components/User/PurchasedList.js
client/src/components/User/ReservedList.js
client/src/components/User/SaleList.js
client/src/components/User/WishItem.js
client/src/styles/user/PurchasedList.module.css
client/src/styles/user/ReservedList.module.css
client/src/styles/user/SaleList.module.css
client/src/styles/user/UserInfo.module.css
client/src/styles/user/WishList.module.css

Docs: 유저메뉴에서 찜목록 삭제
Docs: 구매완료 상품 prodInfo에 price도 추가, 임의 상품 한개 더 추가
Docs: prodInfo에 price도 추가, 구매하기 버튼 삭제
Design: 구매완료상품 반응형
Design: 구매진행상품 반응형
Design: 판매 상품반응형 제작
Design: 유저정보 살짝 수정

Design: 찜목록 반응형

---

client/src/_actions/productAction.js
client/src/_actions/type.js
client/src/_reducers/productReducer.js
client/src/components/Detail/DetailSlide.js
client/src/pages/AddProduct/AddProduct.js

Feat: AddProduct 입력값 예외 처리

---

server/controllers/productController.js
server/routes/product.js
server/services/product.js
server/utils/dataParsers.js

Feat: deleteProduct API 추가

---

client/src/components/User/SaleList.js
client/src/pages/User/UserInfo.js

Feat: 판매상품 컴포넌트 구현

---

client/package-lock.json
client/src/components/Banner/Banner.js
client/src/styles/banner/Banner.module.css

Design: 배너페이지 반응형 추가

---

client/src/components/User/SaleList.js
client/src/styles/user/SaleList.module.css
client/src/styles/user/UserInfo.module.css

Design: 내정보 자기소개란 overflow 속성을 이용하여 스크롤 추가

Feat: 내정보 판매상품에 상품 상태 표시

---

client/src/styles/banner/Banner.module.css
client/src/styles/manual/Manual.module.css

Design: 배너 반응형 추가
Design: 배너 반응형 수정

Design: 메뉴얼 페이지 반응형

---

client/src/pages/Auth/Login.js
client/src/styles/auth/Login.module.css
client/src/styles/product/RecentProducts.module.css

Design: 이미지 사이즈 비율 조정
Docs: 발표자료 최신화

Design: 로그인 창 불필요한 여백 제거

---

client/src/pages/Auth/Login.js

Feat: 카카오, 구글 로그인 알림 추가

---

client/src/components/Chat/ChatRoom.js
client/src/styles/chat/Chat.module.css

Design: 채팅방 반응형 제작

---

client/src/components/Detail/DetailSlide.js
client/src/components/Headers/UserMenu.js
client/src/components/User/ReservedList.js
client/src/components/User/WishItem.js
client/src/pages/Home/Home.js
client/src/styles/chat/Chat.module.css
client/src/styles/headers/MyWallet.module.css
client/src/styles/home/Home.module.css
client/src/styles/product/ReactMinimalSideNavigation.css
client/src/styles/user/ReservedList.module.css
client/src/styles/user/UserInfo.module.css

구매진행상품 구매확정 버튼 조건부 기능 추가
구매진행상품 UI 미완성

Feat: 구매확정 버튼 조건부 기능 추가

---

client/src/components/User/PurchasedList.js
client/src/components/User/WishItem.js
client/src/styles/user/PurchasedList.module.css
client/src/styles/user/ReservedList.module.css
client/src/styles/user/UserInfo.module.css
client/src/styles/user/WishList.module.css

Refactor: deleteBtn 삭제
Design: 이미지 비율 변경
Remove: 필요 없는 코드 삭제

Feat: 찜목록 상품 상태 표시

---

client/src/components/User/PurchasedList.js
client/src/styles/user/PurchasedList.module.css
client/src/styles/user/ReservedList.module.css
client/src/styles/user/SaleList.module.css

Design: 구매완료상품 UI 개선

---

client/src/styles/detail/DetailSlide.module.css
client/src/styles/product/RecentProducts.module.css

Design: 구매하기 상품 반응형 수정

---

client/src/styles/detail/RelateProductSlide.module.css
client/src/styles/detail/styles.css
client/src/styles/home/Home.module.css
client/src/styles/product/Product.module.css
client/src/styles/product/ProductCard.module.css
client/src/styles/product/RecentProducts.module.css
client/src/styles/user/PurchasedList.module.css
client/src/styles/user/ReservedList.module.css
client/src/styles/user/SaleList.module.css
client/src/styles/user/WishList.module.css

Design: 홈 최근등록상품 넓이 수정
Design: 반응형시 상품 넓이 수정
Design: 구매페이지 상품 이미지 크기 수정
Design: 최근등록상품 사진 크기 수정. wrap크기 조절
Design: 내정보에서 제목 길면 ...처리
Design: 연관상품 호버 추가
Design: 배너 모서리 수정
Design: 카드 border-radius값 수정

Design: 연관상품 사진 크기 수정

---

client/src/components/Receipt/DepositReceipt.js
client/src/components/Receipt/ReleaseReceipt.js
client/src/components/User/PurchasedList.js
client/src/components/User/ReservedList.js
client/src/styles/detail/styles.css
client/src/styles/receipt/TransactionDetailReceipt.module.css
client/src/styles/user/PurchasedList.module.css
client/src/styles/user/SaleList.module.css

판매상품, 구매완료상품, 영수증 UI 개선
트랜잭션 정보 삭제

Fix: 트랜잭션 정보 삭제
